# Build stage
FROM node:25-alpine3.21

# Set the working directory
WORKDIR /app

# Copy the source code
COPY internal/server/nodejs/ ./

# Install dependencies
RUN npm install

# Start the server
CMD ["node", "index.js"]
