services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: >
      redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./internal/services/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - RI_REDIS_HOST=${REDIS_HOST}
      - RI_REDIS_ALIAS=${REDIS_ALIAS}
      - RI_REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  redis_data: