// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: internal/server/sse/grpc/notifications/notifications.proto

package notifications

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SenderId      uint32                 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Entity        string                 `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
	EntityId      uint32                 `protobuf:"varint,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Action        string                 `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_internal_server_sse_grpc_notifications_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_sse_grpc_notifications_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_internal_server_sse_grpc_notifications_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Notification) GetSenderId() uint32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Notification) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *Notification) GetEntityId() uint32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_internal_server_sse_grpc_notifications_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_sse_grpc_notifications_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_internal_server_sse_grpc_notifications_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_server_sse_grpc_notifications_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_sse_grpc_notifications_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_server_sse_grpc_notifications_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_internal_server_sse_grpc_notifications_notifications_proto protoreflect.FileDescriptor

const file_internal_server_sse_grpc_notifications_notifications_proto_rawDesc = "" +
	"\n" +
	":internal/server/sse/grpc/notifications/notifications.proto\x12\rnotifications\"\xe9\x01\n" +
	"\fNotification\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\rR\bsenderId\x12\x16\n" +
	"\x06entity\x18\x03 \x01(\tR\x06entity\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\rR\bentityId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x16\n" +
	"\x06action\x18\a \x01(\tR\x06action\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\t \x01(\tR\x04data\"0\n" +
	"\x14NotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1d\n" +
	"\aMessage\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body2\xad\x01\n" +
	"\x14NotificationsService\x12V\n" +
	"\x10SendNotification\x12\x1b.notifications.Notification\x1a#.notifications.NotificationResponse\"\x00\x12=\n" +
	"\tHeartbeat\x12\x16.notifications.Message\x1a\x16.notifications.Message\"\x00B,Z*unipilot/internal/server/sse/notificationsb\x06proto3"

var (
	file_internal_server_sse_grpc_notifications_notifications_proto_rawDescOnce sync.Once
	file_internal_server_sse_grpc_notifications_notifications_proto_rawDescData []byte
)

func file_internal_server_sse_grpc_notifications_notifications_proto_rawDescGZIP() []byte {
	file_internal_server_sse_grpc_notifications_notifications_proto_rawDescOnce.Do(func() {
		file_internal_server_sse_grpc_notifications_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_server_sse_grpc_notifications_notifications_proto_rawDesc), len(file_internal_server_sse_grpc_notifications_notifications_proto_rawDesc)))
	})
	return file_internal_server_sse_grpc_notifications_notifications_proto_rawDescData
}

var file_internal_server_sse_grpc_notifications_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_server_sse_grpc_notifications_notifications_proto_goTypes = []any{
	(*Notification)(nil),         // 0: notifications.Notification
	(*NotificationResponse)(nil), // 1: notifications.NotificationResponse
	(*Message)(nil),              // 2: notifications.Message
}
var file_internal_server_sse_grpc_notifications_notifications_proto_depIdxs = []int32{
	0, // 0: notifications.NotificationsService.SendNotification:input_type -> notifications.Notification
	2, // 1: notifications.NotificationsService.Heartbeat:input_type -> notifications.Message
	1, // 2: notifications.NotificationsService.SendNotification:output_type -> notifications.NotificationResponse
	2, // 3: notifications.NotificationsService.Heartbeat:output_type -> notifications.Message
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type
}

func init() { file_internal_server_sse_grpc_notifications_notifications_proto_init() }
func file_internal_server_sse_grpc_notifications_notifications_proto_init() {
	if File_internal_server_sse_grpc_notifications_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_server_sse_grpc_notifications_notifications_proto_rawDesc), len(file_internal_server_sse_grpc_notifications_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_server_sse_grpc_notifications_notifications_proto_goTypes,
		DependencyIndexes: file_internal_server_sse_grpc_notifications_notifications_proto_depIdxs,
		MessageInfos:      file_internal_server_sse_grpc_notifications_notifications_proto_msgTypes,
	}.Build()
	File_internal_server_sse_grpc_notifications_notifications_proto = out.File
	file_internal_server_sse_grpc_notifications_notifications_proto_goTypes = nil
	file_internal_server_sse_grpc_notifications_notifications_proto_depIdxs = nil
}
