package server

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"time"

	"gorm.io/gorm"

	"unipilot/internal/models/note"
	"unipilot/internal/models/user"
	"unipilot/internal/server"
	"unipilot/internal/services/gemini"
)

// GetNoteHandler retrieves all notes belonging to the authenticated user.
// Returns a list of notes converted to map format for consistent JSON serialization.
// Provides comprehensive note data for user's note management interface.
//
// HTTP Method: GET
// Content-Type: Not required (no request body expected)
//
// Request Body: None required (user context extracted from JWT token)
//
// Response (200 OK):
//   - message: Success message
//   - notes: Array of note objects (as maps) with all note details
//
// Authentication: Required (AuthMiddleware) - extracts user from JWT token
//
// Database Operations:
//   - Reads from `notes` table filtered by `user_id`
//   - No caching strategy implemented (direct database access)
//
// Security Features:
//   - User can only access their own notes (user_id filtering)
//   - Uses ToMap() method for safe JSON serialization
//   - No sensitive data exposure in note objects
//
// Error Responses:
//   - 401 Unauthorized: Invalid or missing JWT token
//   - 500 Internal Server Error: Database query failure
//
// Side Effects:
//   - Logs successful retrieval with note count for monitoring
//   - No database modifications (read-only operation)
func GetNoteHandler(w http.ResponseWriter, r *http.Request) {
	// Step 1: Extract context values from middleware (user and database connection)
	currentUser := r.Context().Value("user").(user.User)
	db := r.Context().Value("db").(*gorm.DB)
	userID := currentUser.ID

	// Step 2: Query user's notes from database
	var notes []note.Note
	if err := db.Where("user_id = ?", userID).Find(&notes).Error; err != nil {
		server.ResponseError(r.Context(), w, err, http.StatusInternalServerError, "Error getting notes from database",
			"tags", []string{"NOTES", "DB"},
		)
		return
	}

	// Step 3: Convert notes to safe map format for JSON response
	var notesMap []map[string]string
	for _, n := range notes {
		notesMap = append(notesMap, n.ToMap())
	}

	// Step 4: Send successful response with note data
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"message": "User's notes retrieved successfully",
		"notes":   notesMap,
	})

	// Step 5: Log successful retrieval with note count for monitoring
}

// CreateNoteHandler creates a new note for the authenticated user with AI-powered content generation.
// Validates input data, optionally generates content using Google Gemini AI, creates note record
// using database transactions, and prepares for future notification distribution to linked users.
//
// HTTP Method: POST
// Content-Type: application/json
//
// Request Body:
//   - user_id: User identifier (string, optional - overridden by JWT context)
//   - course_code: Associated course code (string, required)
//   - title: Note title (string, required)
//   - subject: Note subject/topic (string, required)
//   - content: Note content (string, optional - generated by AI if empty)
//   - keywords: Note keywords (string, optional - generated by AI if empty)
//   - videos: Associated video links (string, optional)
//
// Response (200 OK):
//   - message: Success message
//   - note: Created note object (as map) with all details including AI-generated content
//
// Authentication: Required (AuthMiddleware) - extracts user from JWT token
//
// AI Integration (Google Gemini):
//   - Automatically generates content and keywords if both are empty in request
//   - Uses title, subject, and course code as context for AI generation
//   - Provides intelligent note scaffolding for educational content
//   - Handles AI service failures gracefully with error responses
//
// Database Operations:
//   - Creates record in `notes` table using transaction for atomicity
//   - Validates note ownership and course association
//   - Retrieves complete note data with relationships for response
//
// Notification System (Prepared but Commented):
//   - Code prepared for SSE notifications to course-linked users
//   - Currently disabled pending Docker deployment
//   - Will notify collaborators when notes are shared on courses
//
// Security Features:
//   - User isolation (notes belong to authenticated user)
//   - Transaction rollback on any failure for data consistency
//   - Input validation for required fields
//   - Safe JSON serialization with ToMap() method
//
// Error Responses:
//   - 400 Bad Request: Invalid JSON, missing required fields
//   - 401 Unauthorized: Invalid or missing JWT token
//   - 409 Conflict: Note creation failure (constraint violations)
//   - 500 Internal Server Error: Database operations, AI generation, or processing failures
//
// Side Effects:
//   - Creates note record in database
//   - May call Google Gemini AI service for content generation
//   - Logs note creation with performance metrics
//   - Prepares notification data for future SSE implementation
func CreateNoteHandler(w http.ResponseWriter, r *http.Request) {
	// Step 1: Extract context values from middleware (user and database connection)
	currentUser := r.Context().Value("user").(user.User)
	db := r.Context().Value("db").(*gorm.DB)
	userID := currentUser.ID

	// Step 2: Begin database transaction for atomic note creation
	tx := db.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// Step 3: Define and parse note creation request structure
	var input struct {
		UserID     string `json:"user_id"`
		CourseCode string `json:"course_code"`
		Title      string `json:"title"`
		Subject    string `json:"subject"`
		Content    string `json:"content"`
		Keywords   string `json:"keywords"`
		Videos     string `json:"videos"`
	}

	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		server.ResponseError(r.Context(), w, err, http.StatusBadRequest, "Invalid request body",
			"tags", []string{"NOTES", "REQUEST"},
		)
		return
	}

	// Step 4: Validate all required fields for note creation
	// Validate all required fields
	if input.CourseCode == "" || input.Title == "" || input.Subject == "" {
		err := fmt.Errorf("missing required fields: course code: %s, title: %s, subject: %s", input.CourseCode, input.Title, input.Subject)
		server.ResponseError(r.Context(), w, err, http.StatusBadRequest, "Missing required fields",
			"tags", []string{"NOTES", "MISSING_REQUIRED_FIELDS"},
		)
		return
	}

	// Step 5: Prepare content and keywords, with AI generation fallback
	keywords := input.Keywords
	content := input.Content

	// Generate note content using Gemini AI if both keywords and content are missing
	if keywords == "" && content == "" {
		// Step 6: Generate AI-powered content using Google Gemini service
		// Generate content and keywords using Gemini
		geminiRequest := &gemini.GeminiRequest{
			Title:      input.Title,
			Subject:    input.Subject,
			CourseName: input.CourseCode,
		}

		geminiResponse, err := gemini.GenerateNote(geminiRequest)
		if err != nil {
			server.ResponseError(r.Context(), w, err, http.StatusInternalServerError, "Error generating note content with Gemini",
				"tags", []string{"NOTES", "GEMINI"},
			)
			return
		}

		keywords = geminiResponse.Keywords
		content = geminiResponse.Content
	}

	// Step 7: Construct note object with validated data and AI-generated content
	nVal := note.Note{
		UserID:     userID,
		CourseCode: input.CourseCode,
		Title:      input.Title,
		Subject:    input.Subject,
		Videos:     input.Videos,
		Keywords:   keywords,
		Content:    content,
	}

	// Step 8: Create note record in database within transaction
	result := tx.Create(&nVal)
	if result.Error != nil {
		tx.Rollback()
		server.ResponseError(r.Context(), w, result.Error, http.StatusConflict, "Error creating note in database",
			"tags", []string{"NOTES", "DB"},
		)
		return
	}

	// Step 9: Convert note to safe map format for JSON response
	// Convert to map safely
	noteMap := nVal.ToMap()
	if noteMap == nil {
		tx.Rollback()
		server.ResponseError(r.Context(), w, fmt.Errorf("failed to process note data"), http.StatusInternalServerError, "Error processing note data",
			"tags", []string{"NOTES", "MARSHALLING"},
		)
		return
	}

	// Step 10: Commit transaction after successful note creation
	tx.Commit()

	// Step 11: Prepare notification data for future SSE implementation
	// gRPC -> c : TO BE MOVE IN DOCKER
	// Send a notification to all the users linked

	newN, err := note.Get_Note_byID(nVal.ID, userID, db)
	if err != nil {
		server.ResponseError(r.Context(), w, err, http.StatusInternalServerError, "Error getting note from database",
			"tags", []string{"NOTES", "DB"},
		)
		return
	}

	// Serialize note data for future notification payload
	// nJson, err := json.Marshal(newN)
	_, err = json.Marshal(newN)
	if err != nil {
		server.LogWarn(r.Context(), "Failed to marshal notification", err,
			"tags", []string{"notification", "network", "low"},
			"error_type", "internal",
		)
	}

	// Get linked users for future notification distribution
	// link_users, err := newN.Course.GetLinkUsers(db)
	_, err = newN.Course.GetLinkUsers(db)
	if err != nil {
		server.LogWarn(r.Context(), "Failed to get users linked to course", err,
			"tags", []string{"course", "db", "medium"},
			"error_type", "database",
		)
	}

	/*if sseServer != nil {
		// 2. Send link info to users via SSE (field data)
		for _,sendeeID := range link_users {
			if sendeeID != userID {
				PrintLog(fmt.Sprintf("sending to : %d ",sendeeID))
				sseServer.SendNotification(
					uint(sendeeID),
					userID,
					models.EntityNote,
					newN.Course.ID,
					notifications.NotificationNoteUpdate,
					newN.Title,
					fmt.Sprintf("%s shared a new note on %s", newN.User.Username, newN.CourseCode),
					"note",
					string(nJson),

				)
			}
		}
	}*/

	// Step 12: Send successful response with created note data
	// Return response
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]interface{}{
		"message": "Note created successfully",
		"note":    noteMap,
	})

	// Step 13: Note creation completed (logged by middleware)
}

// UpdateNoteHandler updates a specific field of an existing note with ownership validation.
// Performs targeted field updates using raw SQL within a database transaction for data
// consistency. Only the note owner can update their notes with automatic timestamp tracking.
//
// HTTP Method: POST/PUT
// Content-Type: application/json
//
// Request Body:
//   - id: Note ID to update (string, required, converted to int)
//   - column: Database column name to update (string, required)
//   - value: New value for the specified column (string, required)
//
// Response (200 OK): No response body, success indicated by status code
//
// Authentication: Required (AuthMiddleware) - extracts user from JWT token
//
// Database Operations:
//   - Validates note ownership by user_id before allowing updates
//   - Updates specified column in `notes` table using raw SQL
//   - Automatically updates `updated_at` timestamp for audit trail
//   - Uses database transaction for atomicity and consistency
//
// Security Features:
//   - Note ownership verification before allowing any updates
//   - Transaction rollback on any failure for data consistency
//   - Input validation for note ID format and conversion
//
// Security Warning:
//   - Uses string interpolation for column name - column should be
//     validated to prevent SQL injection attacks in production environments.
//   - Transaction rollback on any failure for data consistency
//
// Error Responses:
//   - 400 Bad Request: Invalid JSON body, malformed note ID
//   - 401 Unauthorized: Invalid or missing JWT token
//   - 500 Internal Server Error: Database operations failure, note not found
//
// Side Effects:
//   - Modifies note record in database with timestamp update
//   - Logs successful updates with change details for audit trail
//   - No notification system integration (updates are silent)
func UpdateNoteHandler(w http.ResponseWriter, r *http.Request) {
	// Step 1: Extract context values from middleware (user and database connection)
	currentUser := r.Context().Value("user").(user.User)
	db := r.Context().Value("db").(*gorm.DB)
	userID := currentUser.ID

	// Step 2: Begin database transaction for atomic note update
	tx := db.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// Step 3: Define and parse note update request structure
	var updateData struct {
		ID     string `json:"id"`
		Value  string `json:"value"`
		Column string `json:"column"`
	}

	err := json.NewDecoder(r.Body).Decode(&updateData)
	if err != nil {
		server.ResponseError(r.Context(), w, err, http.StatusBadRequest, "Invalid request body",
			"tags", []string{"NOTES", "REQUEST"},
		)
		return
	}

	// Step 4: Convert note ID from string to integer for database query
	int_id, err := strconv.Atoi(updateData.ID)
	if err != nil {
		server.ResponseError(r.Context(), w, err, http.StatusBadRequest, "Error converting note ID to int",
			"tags", []string{"NOTES", "INVALID_NOTE_ID"},
		)
		return
	}

	// Step 5: Validate note exists and user has ownership permissions
	n, err := note.Get_Note_byID(uint(int_id), userID, tx)
	if err != nil {
		tx.Rollback()
		server.ResponseError(r.Context(), w, err, http.StatusInternalServerError, "Error getting note from database",
			"tags", []string{"NOTES", "DB"},
		)
		return
	}

	// Step 6: Execute raw SQL update with automatic timestamp tracking
	if err := tx.Exec(fmt.Sprintf("UPDATE notes SET %s = ?, updated_at = ? WHERE id = ?", updateData.Column),
		updateData.Value, time.Now().Format(time.RFC3339), n.ID).Error; err != nil {
		tx.Rollback()
		server.ResponseError(r.Context(), w, err, http.StatusInternalServerError, "Error updating note in database",
			"tags", []string{"NOTES", "DB"},
		)
		return
	}

	// Step 7: Commit transaction after successful update
	tx.Commit()

	// Step 8: Note update completed (logged by middleware)
}
