package server

import (
	"bufio"
	"context"
	"encoding/json"
	Errors "errors"
	"fmt"

	"github.com/gofiber/fiber/v2"
	"gorm.io/gorm"

	"unipilot/internal/errors"
	"unipilot/internal/models"
	"unipilot/internal/server"
	"unipilot/internal/server/sse/grpc/messages"
	"unipilot/internal/services/gemini"
)

// GetNoteHandler retrieves all notes belonging to the authenticated models.
// Returns a list of notes converted to map format for consistent JSON serialization.
// Provides comprehensive note data for user's note management interface.
//
// HTTP Method: GET
// Content-Type: Not required (no request body expected)
//
// Request Body: None required (user context extracted from JWT token)
//
// Response (200 OK):
//   - message: Success message
//   - notes: Array of note objects (as maps) with all note details
//
// Authentication: Required (AuthMiddleware) - extracts user from JWT token
//
// Database Operations:
//   - Reads from `notes` table filtered by `user_id`
//   - No caching strategy implemented (direct database access)
//
// Security Features:
//   - User can only access their own notes (user_id filtering)
//   - Uses ToMap() method for safe JSON serialization
//   - No sensitive data exposure in note objects
//
// Error Responses:
//   - 401 Unauthorized: Invalid or missing JWT token
//   - 500 Internal Server Error: Database query failure
//
// Side Effects:
//   - Logs successful retrieval with note count for monitoring
//   - No database modifications (read-only operation)
func GetNotesHandler(c *fiber.Ctx) error {

	ctx := c.UserContext()
	db, err := server.GetDB(ctx)
	if err != nil {
		return errors.WrapServer(err, errors.InternalError, "DB not found in context", fiber.StatusInternalServerError)
	}
	currentUser, err := server.GetUser(ctx)
	if err != nil {
		return errors.WrapServer(err, errors.InternalError, "User not found in context", fiber.StatusInternalServerError)
	}
	userID := currentUser.ID

	// Step 2: Query user's notes from database
	notes, err := models.GetNotes(userID, db)
	if err != nil {
		return errors.WrapServer(err, errors.DBQueryFailed, "Error getting notes from database", fiber.StatusInternalServerError)
	}

	// Step 4: Send successful response with note data
	return c.JSON(notes)
}

// CreateNoteHandler creates a new note for the authenticated user with AI-powered content generation.
// Validates input data, optionally generates content using Google Gemini AI, creates note record
// using database transactions, and prepares for future notification distribution to linked users.
//
// HTTP Method: POST
// Content-Type: application/json
// Request Body:
//   - user_id: User identifier (string, optional - overridden by JWT context)
//   - course_code: Associated course code (string, required)
//   - title: Note title (string, required)
//   - subject: Note subject/topic (string, required)
//   - content: Note content (string, optional - generated by AI if empty)
//   - videos: Associated video links (string, optional)
//
// Response (200 OK):
//   - message: Success message
//   - note: Created note object (as map) with all details including AI-generated content
//
// Authentication: Required (AuthMiddleware) - extracts user from JWT token
//
// AI Integration (Google Gemini):
//   - Automatically generates content if empty in request
//   - Uses title, subject, and course code as context for AI generation
//   - Provides intelligent note scaffolding for educational content
//   - Handles AI service failures gracefully with error responses
//
// Database Operations:
//   - Creates record in `notes` table using transaction for atomicity
//   - Validates note ownership and course association
//   - Retrieves complete note data with relationships for response
//
// Notification System (Prepared but Commented):
//   - Code prepared for SSE notifications to course-linked users
//   - Currently disabled pending Docker deployment
//   - Will notify collaborators when notes are shared on courses
//
// Security Features:
//   - User isolation (notes belong to authenticated user)
//   - Transaction rollback on any failure for data consistency
//   - Input validation for required fields
//   - Safe JSON serialization with ToMap() method
//
// Error Responses:
//   - 400 Bad Request: Invalid JSON, missing required fields
//   - 401 Unauthorized: Invalid or missing JWT token
//   - 409 Conflict: Note creation failure (constraint violations)
//   - 500 Internal Server Error: Database operations, AI generation, or processing failures
//
// Side Effects:
//   - Creates note record in database
//   - May call Google Gemini AI service for content generation
//   - Logs note creation with performance metrics
//   - Prepares notification data for future SSE implementation
func CreateNoteHandler(c *fiber.Ctx) error {

	ctx := c.UserContext()
	db, err := server.GetDB(ctx)
	if err != nil {
		return errors.WrapServer(err, errors.InternalError, "DB not found in context", fiber.StatusInternalServerError)
	}
	currentUser, err := server.GetUser(ctx)
	if err != nil {
		return errors.WrapServer(err, errors.InternalError, "User not found in context", fiber.StatusInternalServerError)
	}
	userID := currentUser.ID

	var newNote models.Note
	// Step 3: Define and parse note creation request structure
	if err := c.BodyParser(&newNote); err != nil {
		return errors.WrapServer(err, errors.ReqBodyInvalid, "Invalid request body", fiber.StatusBadRequest)
	}

	if err := newNote.Validate(); err != nil {
		return errors.Inherit(err, errors.ValidationInvalid).ToServerError(fiber.StatusBadRequest)
	}

	result := db.Preload("Course").Create(&newNote).First(&newNote)
	if result.Error != nil {
		if Errors.Is(result.Error, gorm.ErrDuplicatedKey) {
			return errors.WrapServer(result.Error, errors.DBConstraintViolation, "Note already exists", fiber.StatusConflict)
		}
		return errors.WrapServer(result.Error, errors.DBQueryFailed, "Note creating assignment in database", fiber.StatusInternalServerError)
	}

	// Step 14: Send SSE notifications to linked users via gRPC (if available)
	go func() {
		clusterRootID := newNote.ClusterRoot()

		if GrpcClient != nil && newNote.Course.IsInCluster(db) && !newNote.IsCopy() {
			users_course, err := CacheService.GetClusterUsers(context.Background(), clusterRootID, db)

			if err != nil {
				server.LogWarn(context.Background(), errors.WrapServer(err, errors.DBQueryFailed, "Error getting users linked to course", fiber.StatusInternalServerError))
				return
			}

			for _, sendeeID := range users_course {
				if sendeeID == userID {
					continue
				}
				_, err := (*GrpcClient).SendMessage(context.Background(),
					&messages.Message{
						ReceiverId: sendeeID,
						SenderId:   userID,
						Title:      newNote.Title,
						Message:    fmt.Sprintf("%s shared a new note on %s", currentUser.Username, newNote.Course.Code),
						Data:       []byte(""),
						Type:       string(models.MessageNoContent),
					},
				)
				if err != nil {
					server.LogWarn(context.Background(), errors.WrapServer(err, errors.GRPCFailed, "Failed to send notification", fiber.StatusInternalServerError))
				}

			}

			CacheService.AddCourseNote(context.Background(), clusterRootID, newNote.ID)
			CacheService.SetNotes(context.Background(), []*models.Note{&newNote})
		}
	}()

	// Step 12: Send successful response with created note data
	return c.SendStatus(fiber.StatusCreated)
}

func CreateNoteStreamHandler(c *fiber.Ctx) error {

	ctx := c.UserContext()
	db, err := server.GetDB(ctx)
	if err != nil {
		return errors.WrapServer(err, errors.InternalError, "DB not found in context", fiber.StatusInternalServerError)
	}

	// Step 1: Define and parse note creation request structure
	var newNote models.LocalNote
	if err := c.BodyParser(&newNote); err != nil {
		return errors.WrapServer(err, errors.ReqBodyInvalid, "Invalid request body", fiber.StatusBadRequest)
	}

	if err := newNote.Validate(); err != nil {
		return errors.Inherit(err, errors.ValidationInvalid).ToServerError(fiber.StatusBadRequest)
	}

	// Step 3: Set up SSE headers for streaming response
	c.Set("Content-Type", "text/event-stream")
	c.Set("Cache-Control", "no-cache")
	c.Set("Connection", "keep-alive")
	c.Set("Access-Control-Allow-Origin", "*")
	c.Set("X-Accel-Buffering", "no")

	// Step 4: Generate AI-powered content using Google Gemini service
	// Generate content and keywords using Gemini

	course, err := models.GetCourse(newNote.CourseID, db)
	if err != nil {
		return errors.WrapServer(err, errors.DBQueryFailed, "Error getting course from database", fiber.StatusInternalServerError)
	}

	geminiRequest := &gemini.GeminiRequest{
		Title:      newNote.Title,
		Subject:    newNote.Subject,
		CourseName: course.Name,
	}

	var geminiErr error
	c.Context().SetBodyStreamWriter(func(w *bufio.Writer) {
		// Stream chunks from Gemini to client with field-specific events
		err := gemini.GenerateNoteStream(geminiRequest, func(chunk string) error {
			// Use JSON encoding to reliably preserve Gemini's exact format
			jsonData, err := json.Marshal(map[string]string{"chunk": chunk})
			if err != nil {
				return errors.WrapServer(err, errors.ProcJSONMarshalFailed, "Failed to marshal note chunk", fiber.StatusInternalServerError)
			}
			// Format as SSE event with JSON-encoded data
			fmt.Fprintf(w, "data: %s\n\n", jsonData)
			return w.Flush()
		})

		if err != nil {
			geminiErr = err
			// Send error event to client with JSON encoding
			errorData, _ := json.Marshal(map[string]string{"error": err.Error()})
			fmt.Fprintf(w, "event: error\ndata: %s\n\n", errorData)
			w.Flush()
			return
		}

		// Send completion event with JSON encoding
		completeData, _ := json.Marshal(map[string]string{"status": "done"})
		fmt.Fprintf(w, "event: complete\ndata: %s\n\n", completeData)
		w.Flush()
	})

	if geminiErr != nil {
		return errors.WrapServer(geminiErr, errors.ProcDataProcessingFailed, "Error generating note content with Gemini", fiber.StatusInternalServerError)

	}

	return nil // No response body for streaming
}

// UpdateNoteHandler updates a specific field of an existing note with ownership validation.
// Performs targeted field updates using raw SQL within a database transaction for data
// consistency. Only the note owner can update their notes with automatic timestamp tracking.
//
// HTTP Method: POST/PUT
// Content-Type: application/json
//
// Request Body:
//   - id: Note ID to update (string, required, converted to int)
//   - column: Database column name to update (string, required)
//   - value: New value for the specified column (string, required)
//
// Response (200 OK): No response body, success indicated by status code
//
// Authentication: Required (AuthMiddleware) - extracts user from JWT token
//
// Database Operations:
//   - Validates note ownership by user_id before allowing updates
//   - Updates specified column in `notes` table using raw SQL
//   - Automatically updates `updated_at` timestamp for audit trail
//   - Uses database transaction for atomicity and consistency
//
// Security Features:
//   - Note ownership verification before allowing any updates
//   - Transaction rollback on any failure for data consistency
//   - Input validation for note ID format and conversion
//
// Security Warning:
//   - Uses string interpolation for column name - column should be
//     validated to prevent SQL injection attacks in production environments.
//   - Transaction rollback on any failure for data consistency
//
// Error Responses:
//   - 400 Bad Request: Invalid JSON body, malformed note ID
//   - 401 Unauthorized: Invalid or missing JWT token
//   - 500 Internal Server Error: Database operations failure, note not found
//
// Side Effects:
//   - Modifies note record in database with timestamp update
//   - Logs successful updates with change details for audit trail
//   - No notification system integration (updates are silent)
func UpdateNoteHandler(c *fiber.Ctx) error {

	ctx := c.UserContext()
	db, err := server.GetDB(ctx)
	if err != nil {
		return errors.WrapServer(err, errors.InternalError, "DB not found in context", fiber.StatusInternalServerError)
	}

	var noteID string
	if noteID = c.Params("id"); noteID == "" {
		return errors.WrapServer(fmt.Errorf("note ID required"), errors.ReqParamMissing, "Note ID required", fiber.StatusBadRequest)
	}

	// Step 3: Define and parse note update request structure
	var updateData struct {
		Value  string `json:"value"`
		Column string `json:"column"`
	}

	if err := c.BodyParser(&updateData); err != nil {
		return errors.WrapServer(err, errors.ReqBodyInvalid, "Invalid request body", fiber.StatusBadRequest)
	}

	if updateData.Column == "" || updateData.Value == "" {
		return errors.WrapServer(fmt.Errorf("column and value are required"), errors.ReqParamMissing, "Column and value are required", fiber.StatusBadRequest)
	}

	note := models.Note{
		Base: models.Base{ID: noteID},
	}
	if err := db.Preload("Course").Model(&note).Where("id = ?", noteID).Update(updateData.Column, updateData.Value).First(&note).Error; err != nil {

		if Errors.Is(err, gorm.ErrDuplicatedKey) {
			return errors.WrapServer(err, errors.DBConstraintViolation, "Note already exists", fiber.StatusConflict)
		}

		return errors.WrapServer(err, errors.DBQueryFailed, "Error updating note in database", fiber.StatusInternalServerError)
	}

	go func() {
		if note.Course.IsInCluster(db) && !note.IsCopy() {
			CacheService.SetNotes(context.Background(), []*models.Note{&note})
		}
	}()

	// Step 8: Note update completed (logged by middleware)
	return c.SendStatus(fiber.StatusNoContent)
}

func DeleteNoteHandler(c *fiber.Ctx) error {

	ctx := c.UserContext()
	db, err := server.GetDB(ctx)
	if err != nil {
		return errors.WrapServer(err, errors.InternalError, "DB not found in context", fiber.StatusInternalServerError)
	}

	var noteID string
	if noteID = c.Params("id"); noteID == "" {
		return errors.WrapServer(fmt.Errorf("note ID required"), errors.ReqParamMissing, "Note ID required", fiber.StatusBadRequest)
	}

	note, err := models.GetNote(noteID, db.Preload("Course"))
	if err != nil {
		return errors.WrapServer(err, errors.DBQueryFailed, "Error getting note from database", fiber.StatusInternalServerError)
	}
	if err := db.Delete(&note).Error; err != nil {
		return errors.WrapServer(err, errors.DBQueryFailed, "Error deleting note from database", fiber.StatusInternalServerError)
	}

	go func() {
		if note.Course.IsInCluster(db) && !note.IsCopy() {
			clusterRootID := note.ClusterRoot()
			CacheService.RemoveCourseNote(context.Background(), clusterRootID, noteID)
			CacheService.DeleteNote(context.Background(), noteID)
		}
	}()

	return c.SendStatus(fiber.StatusNoContent)
}
