package server

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"time"

	"github.com/gofiber/fiber/v2"
	"gorm.io/gorm"

	"unipilot/internal/models/note"
	"unipilot/internal/models/user"
	"unipilot/internal/server"
	"unipilot/internal/services/gemini"
)

// GetNoteHandler retrieves all notes belonging to the authenticated user.
// Returns a list of notes converted to map format for consistent JSON serialization.
// Provides comprehensive note data for user's note management interface.
//
// HTTP Method: GET
// Content-Type: Not required (no request body expected)
//
// Request Body: None required (user context extracted from JWT token)
//
// Response (200 OK):
//   - message: Success message
//   - notes: Array of note objects (as maps) with all note details
//
// Authentication: Required (AuthMiddleware) - extracts user from JWT token
//
// Database Operations:
//   - Reads from `notes` table filtered by `user_id`
//   - No caching strategy implemented (direct database access)
//
// Security Features:
//   - User can only access their own notes (user_id filtering)
//   - Uses ToMap() method for safe JSON serialization
//   - No sensitive data exposure in note objects
//
// Error Responses:
//   - 401 Unauthorized: Invalid or missing JWT token
//   - 500 Internal Server Error: Database query failure
//
// Side Effects:
//   - Logs successful retrieval with note count for monitoring
//   - No database modifications (read-only operation)
func GetNotesHandler(c *fiber.Ctx) error {
	// Step 1: Extract context values from middleware (user and database connection)
	currentUser := c.Locals("user").(user.User)
	db := c.Locals("db").(*gorm.DB)
	userID := currentUser.ID

	// Step 2: Query user's notes from database
	var notes []note.Note
	if err := db.Where("user_id = ?", userID).Find(&notes).Error; err != nil {
		return server.ResponseError(c, err, fiber.StatusInternalServerError, "Error getting notes from database",
			"tags", []string{"NOTES", "DB"},
		)
	}

	// Step 3: Convert notes to safe map format for JSON response
	var notesMap []map[string]string
	for _, n := range notes {
		notesMap = append(notesMap, n.ToMap())
	}

	// Step 4: Send successful response with note data
	return c.JSON(fiber.Map{
		"message": "User's notes retrieved successfully",
		"notes":   notesMap,
	})
}

// CreateNoteHandler creates a new note for the authenticated user with AI-powered content generation.
// Validates input data, optionally generates content using Google Gemini AI, creates note record
// using database transactions, and prepares for future notification distribution to linked users.
//
// HTTP Method: POST
// Content-Type: application/json
//
// Request Body:
//   - user_id: User identifier (string, optional - overridden by JWT context)
//   - course_code: Associated course code (string, required)
//   - title: Note title (string, required)
//   - subject: Note subject/topic (string, required)
//   - content: Note content (string, optional - generated by AI if empty)
//   - videos: Associated video links (string, optional)
//
// Response (200 OK):
//   - message: Success message
//   - note: Created note object (as map) with all details including AI-generated content
//
// Authentication: Required (AuthMiddleware) - extracts user from JWT token
//
// AI Integration (Google Gemini):
//   - Automatically generates content if empty in request
//   - Uses title, subject, and course code as context for AI generation
//   - Provides intelligent note scaffolding for educational content
//   - Handles AI service failures gracefully with error responses
//
// Database Operations:
//   - Creates record in `notes` table using transaction for atomicity
//   - Validates note ownership and course association
//   - Retrieves complete note data with relationships for response
//
// Notification System (Prepared but Commented):
//   - Code prepared for SSE notifications to course-linked users
//   - Currently disabled pending Docker deployment
//   - Will notify collaborators when notes are shared on courses
//
// Security Features:
//   - User isolation (notes belong to authenticated user)
//   - Transaction rollback on any failure for data consistency
//   - Input validation for required fields
//   - Safe JSON serialization with ToMap() method
//
// Error Responses:
//   - 400 Bad Request: Invalid JSON, missing required fields
//   - 401 Unauthorized: Invalid or missing JWT token
//   - 409 Conflict: Note creation failure (constraint violations)
//   - 500 Internal Server Error: Database operations, AI generation, or processing failures
//
// Side Effects:
//   - Creates note record in database
//   - May call Google Gemini AI service for content generation
//   - Logs note creation with performance metrics
//   - Prepares notification data for future SSE implementation
func CreateNoteHandler(c *fiber.Ctx) error {
	// Step 1: Extract context values from middleware (user and database connection)
	currentUser := c.Locals("user").(user.User)
	db := c.Locals("db").(*gorm.DB)
	userID := currentUser.ID

	// Step 2: Begin database transaction for atomic note creation
	tx := db.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// Step 3: Define and parse note creation request structure
	var input note.LocalNote

	if err := c.BodyParser(&input); err != nil {
		return server.ResponseError(c, err, fiber.StatusBadRequest, "Invalid request body",
			"tags", []string{"NOTES", "REQUEST"},
		)
	}

	// Step 4: Validate all required fields for note creation
	// Validate all required fields
	if input.CourseCode == "" || input.Title == "" || input.Subject == "" {
		err := fmt.Errorf("missing required fields: course code: %s, title: %s, subject: %s", input.CourseCode, input.Title, input.Subject)
		return server.ResponseError(c, err, fiber.StatusBadRequest, "Missing required fields",
			"tags", []string{"NOTES", "MISSING_REQUIRED_FIELDS"},
		)
	}

	// Step 5: Prepare content and keywords, with AI generation fallback
	content := input.Content

	// Generate note content using Gemini AI if both keywords and content are missing
	// if keywords == "" && content == "" {
	// 	// Step 6: Generate AI-powered content using Google Gemini service
	// 	// Generate content and keywords using Gemini
	// 	geminiRequest := &gemini.GeminiRequest{
	// 		Title:      input.Title,
	// 		Subject:    input.Subject,
	// 		CourseName: input.CourseCode,
	// 	}

	// 	geminiResponse, err := gemini.GenerateNote(geminiRequest)
	// 	if err != nil {
	// 		return server.ResponseError(c, err, fiber.StatusInternalServerError, "Error generating note content with Gemini",
	// 			"tags", []string{"NOTES", "GEMINI"},
	// 		)
	// 	}

	// 	keywords = geminiResponse.Keywords
	// 	content = geminiResponse.Content
	// }

	// Step 7: Construct note object with validated data and AI-generated content
	nVal := note.Note{
		UserID:     userID,
		CourseCode: input.CourseCode,
		Title:      input.Title,
		Subject:    input.Subject,
		Videos:     input.Videos,
		Content:    content,
	}

	// Step 8: Create note record in database within transaction
	result := tx.Create(&nVal)
	if result.Error != nil {
		tx.Rollback()
		return server.ResponseError(c, result.Error, fiber.StatusConflict, "Error creating note in database",
			"tags", []string{"NOTES", "DB"},
		)
	}

	// Step 9: Convert note to safe map format for JSON response
	// Convert to map safely
	noteMap := nVal.ToMap()
	if noteMap == nil {
		tx.Rollback()
		return server.ResponseError(c, fmt.Errorf("failed to process note data"), fiber.StatusInternalServerError, "Error processing note data",
			"tags", []string{"NOTES", "MARSHALLING"},
		)
	}

	// Step 10: Commit transaction after successful note creation
	tx.Commit()

	// Step 11: Prepare notification data for future SSE implementation
	// gRPC -> c : TO BE MOVE IN DOCKER
	// Send a notification to all the users linked

	newN, err := note.Get_Note_byID(nVal.ID, userID, db)
	if err != nil {
		return server.ResponseError(c, err, fiber.StatusInternalServerError, "Error getting note from database",
			"tags", []string{"NOTES", "DB"},
		)
	}

	// Serialize note data for future notification payload
	// nJson, err := json.Marshal(newN)
	_, err = json.Marshal(newN)
	if err != nil {
		server.LogWarn(context.Background(), "Failed to marshal notification", err,
			"tags", []string{"notification", "network", "low"},
			"error_type", "internal",
		)
	}

	// Get linked users for future notification distribution
	// link_users, err := newN.Course.GetLinkUsers(db)
	_, err = newN.Course.GetLinkUsers(db)
	if err != nil {
		server.LogWarn(context.Background(), "Failed to get users linked to course", err,
			"tags", []string{"course", "db", "medium"},
			"error_type", "database",
		)
	}

	/*if sseServer != nil {
		// 2. Send link info to users via SSE (field data)
		for _,sendeeID := range link_users {
			if sendeeID != userID {
				PrintLog(fmt.Sprintf("sending to : %d ",sendeeID))
				sseServer.SendNotification(
					uint(sendeeID),
					userID,
					models.EntityNote,
					newN.Course.ID,
					notifications.NotificationNoteUpdate,
					newN.Title,
					fmt.Sprintf("%s shared a new note on %s", newN.User.Username, newN.CourseCode),
					"note",
					string(nJson),

				)
			}
		}
	}*/

	// Step 12: Send successful response with created note data
	return c.JSON(fiber.Map{
		"message": "Note created successfully",
		"note":    noteMap,
	})
}

func CreateNoteStreamHandler(c *fiber.Ctx) error {

	// Step 3: Define and parse note creation request structure
	var input note.LocalNote

	if err := c.BodyParser(&input); err != nil {
		return server.ResponseError(c, err, fiber.StatusBadRequest, "Invalid request body",
			"tags", []string{"NOTES", "REQUEST"},
		)
	}

	// Step 4: Validate all required fields for note creation
	// Validate all required fields
	if input.CourseCode == "" || input.Title == "" || input.Subject == "" {
		err := fmt.Errorf("missing required fields: course code: %s, title: %s, subject: %s", input.CourseCode, input.Title, input.Subject)
		return server.ResponseError(c, err, fiber.StatusBadRequest, "Missing required fields",
			"tags", []string{"NOTES", "MISSING_REQUIRED_FIELDS"},
		)
	}

	// Step 5: Set up SSE headers for streaming response
	c.Set("Content-Type", "text/event-stream")
	c.Set("Cache-Control", "no-cache")
	c.Set("Connection", "keep-alive")
	c.Set("Access-Control-Allow-Origin", "*")
	c.Set("X-Accel-Buffering", "no")

	// Step 6: Generate AI-powered content using Google Gemini service
	// Generate content and keywords using Gemini
	geminiRequest := &gemini.GeminiRequest{
		Title:      input.Title,
		Subject:    input.Subject,
		CourseName: input.CourseCode,
	}

	var geminiErr error
	c.Context().SetBodyStreamWriter(func(w *bufio.Writer) {
		// Stream chunks from Gemini to client with field-specific events
		err := gemini.GenerateNoteStream(geminiRequest, func(chunk string) error {
			// Use JSON encoding to reliably preserve Gemini's exact format
			jsonData, err := json.Marshal(map[string]string{"chunk": chunk})
			if err != nil {
				return fmt.Errorf("failed to marshal chunk: %w", err)
			}
			// Format as SSE event with JSON-encoded data
			fmt.Fprintf(w, "data: %s\n\n", jsonData)
			return w.Flush()
		})

		if err != nil {
			geminiErr = err
			// Send error event to client with JSON encoding
			errorData, _ := json.Marshal(map[string]string{"error": err.Error()})
			fmt.Fprintf(w, "event: error\ndata: %s\n\n", errorData)
			w.Flush()
			return
		}

		// Send completion event with JSON encoding
		completeData, _ := json.Marshal(map[string]string{"status": "done"})
		fmt.Fprintf(w, "event: complete\ndata: %s\n\n", completeData)
		w.Flush()
	})

	if geminiErr != nil {
		return server.ResponseError(c, geminiErr, fiber.StatusInternalServerError, "Error generating note content with Gemini",
			"tags", []string{"NOTES", "GEMINI"},
		)

	}

	return nil // No response body for streaming
}

// UpdateNoteHandler updates a specific field of an existing note with ownership validation.
// Performs targeted field updates using raw SQL within a database transaction for data
// consistency. Only the note owner can update their notes with automatic timestamp tracking.
//
// HTTP Method: POST/PUT
// Content-Type: application/json
//
// Request Body:
//   - id: Note ID to update (string, required, converted to int)
//   - column: Database column name to update (string, required)
//   - value: New value for the specified column (string, required)
//
// Response (200 OK): No response body, success indicated by status code
//
// Authentication: Required (AuthMiddleware) - extracts user from JWT token
//
// Database Operations:
//   - Validates note ownership by user_id before allowing updates
//   - Updates specified column in `notes` table using raw SQL
//   - Automatically updates `updated_at` timestamp for audit trail
//   - Uses database transaction for atomicity and consistency
//
// Security Features:
//   - Note ownership verification before allowing any updates
//   - Transaction rollback on any failure for data consistency
//   - Input validation for note ID format and conversion
//
// Security Warning:
//   - Uses string interpolation for column name - column should be
//     validated to prevent SQL injection attacks in production environments.
//   - Transaction rollback on any failure for data consistency
//
// Error Responses:
//   - 400 Bad Request: Invalid JSON body, malformed note ID
//   - 401 Unauthorized: Invalid or missing JWT token
//   - 500 Internal Server Error: Database operations failure, note not found
//
// Side Effects:
//   - Modifies note record in database with timestamp update
//   - Logs successful updates with change details for audit trail
//   - No notification system integration (updates are silent)
func UpdateNoteHandler(c *fiber.Ctx) error {
	// Step 1: Extract context values from middleware (user and database connection)
	currentUser := c.Locals("user").(user.User)
	db := c.Locals("db").(*gorm.DB)
	userID := currentUser.ID

	var int_id int
	var err error
	idStr := c.Params("id")
	if idStr == "" {
		return server.ResponseError(c, fmt.Errorf("note ID required"), fiber.StatusBadRequest, "Note ID required",
			"tags", []string{"NOTES", "INVALID_NOTE_ID"},
		)
	}
	if int_id, err = strconv.Atoi(idStr); err != nil {
		return server.ResponseError(c, err, fiber.StatusBadRequest, "Error converting note ID to int",
			"tags", []string{"NOTES", "INVALID_NOTE_ID"},
		)
	}
	noteID := uint(int_id)

	// Step 2: Begin database transaction for atomic note update
	tx := db.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// Step 3: Define and parse note update request structure
	var updateData struct {
		Value  string `json:"value"`
		Column string `json:"column"`
	}

	if err := c.BodyParser(&updateData); err != nil {
		return server.ResponseError(c, err, fiber.StatusBadRequest, "Invalid request body",
			"tags", []string{"NOTES", "REQUEST"},
		)
	}

	// Step 5: Validate note exists and user has ownership permissions
	n, err := note.Get_Note_byID(noteID, userID, tx)
	if err != nil {
		tx.Rollback()
		return server.ResponseError(c, err, fiber.StatusInternalServerError, "Error getting note from database",
			"tags", []string{"NOTES", "DB"},
		)
	}

	// Step 6: Execute raw SQL update with automatic timestamp tracking
	if err := tx.Exec(fmt.Sprintf("UPDATE notes SET %s = ?, updated_at = ? WHERE id = ?", updateData.Column),
		updateData.Value, time.Now().Format(time.RFC3339), n.ID).Error; err != nil {
		tx.Rollback()
		return server.ResponseError(c, err, fiber.StatusInternalServerError, "Error updating note in database",
			"tags", []string{"NOTES", "DB"},
		)
	}

	// Step 7: Commit transaction after successful update
	tx.Commit()

	// Step 8: Note update completed (logged by middleware)
	return c.JSON(fiber.Map{"message": "Note updated successfully"})
}

func DeleteNoteHandler(c *fiber.Ctx) error {
	// Step 1: Extract context values from middleware (user and database connection)
	db := c.Locals("db").(*gorm.DB)

	idStr := c.Params("id")
	if idStr == "" {
		return server.ResponseError(c, fmt.Errorf("note ID required"), fiber.StatusBadRequest, "Note ID required",
			"tags", []string{"NOTES", "INVALID_NOTE_ID"},
		)
	}
	noteID, err := strconv.Atoi(idStr)
	if err != nil {
		return server.ResponseError(c, err, fiber.StatusBadRequest, "Error converting note ID to int",
			"tags", []string{"NOTES", "INVALID_NOTE_ID"},
		)
	}

	// Step 2: Begin database transaction for atomic note deletion
	if err := note.DeleteNote(uint(noteID), db); err != nil {
		return server.ResponseError(c, err, fiber.StatusInternalServerError, "Error deleting note from database",
			"tags", []string{"NOTES", "DB"},
		)
	}

	return c.JSON(fiber.Map{"message": "Note deleted successfully"})
}
