// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptAssignment(arg1) {
  return window['go']['main']['App']['AcceptAssignment'](arg1);
}

export function AcceptDocument(arg1) {
  return window['go']['main']['App']['AcceptDocument'](arg1);
}

export function AcceptLink(arg1) {
  return window['go']['main']['App']['AcceptLink'](arg1);
}

export function AcceptNote(arg1) {
  return window['go']['main']['App']['AcceptNote'](arg1);
}

export function CreateAssignment(arg1) {
  return window['go']['main']['App']['CreateAssignment'](arg1);
}

export function CreateCourse(arg1) {
  return window['go']['main']['App']['CreateCourse'](arg1);
}

export function CreateDocument(arg1, arg2) {
  return window['go']['main']['App']['CreateDocument'](arg1, arg2);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function DeleteAssignment(arg1) {
  return window['go']['main']['App']['DeleteAssignment'](arg1);
}

export function DeleteCourse(arg1) {
  return window['go']['main']['App']['DeleteCourse'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteNotification(arg1) {
  return window['go']['main']['App']['DeleteNotification'](arg1);
}

export function DownloadDocument(arg1) {
  return window['go']['main']['App']['DownloadDocument'](arg1);
}

export function Follow(arg1) {
  return window['go']['main']['App']['Follow'](arg1);
}

export function GetAssignment(arg1) {
  return window['go']['main']['App']['GetAssignment'](arg1);
}

export function GetAssignmentDocuments(arg1) {
  return window['go']['main']['App']['GetAssignmentDocuments'](arg1);
}

export function GetAssignments() {
  return window['go']['main']['App']['GetAssignments']();
}

export function GetCourse(arg1) {
  return window['go']['main']['App']['GetCourse'](arg1);
}

export function GetCourseAssignments(arg1) {
  return window['go']['main']['App']['GetCourseAssignments'](arg1);
}

export function GetCourses() {
  return window['go']['main']['App']['GetCourses']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetFollowers(arg1) {
  return window['go']['main']['App']['GetFollowers'](arg1);
}

export function GetFollowing(arg1) {
  return window['go']['main']['App']['GetFollowing'](arg1);
}

export function GetNetworkStatus() {
  return window['go']['main']['App']['GetNetworkStatus']();
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function GetNotificationDaemonStatus() {
  return window['go']['main']['App']['GetNotificationDaemonStatus']();
}

export function GetNotifications() {
  return window['go']['main']['App']['GetNotifications']();
}

export function GetRemoteUsers() {
  return window['go']['main']['App']['GetRemoteUsers']();
}

export function GetSubmissionDocuments(arg1) {
  return window['go']['main']['App']['GetSubmissionDocuments'](arg1);
}

export function GetSupportDocuments(arg1) {
  return window['go']['main']['App']['GetSupportDocuments'](arg1);
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function GetUserStorageInfo() {
  return window['go']['main']['App']['GetUserStorageInfo']();
}

export function InstallNotificationDaemon() {
  return window['go']['main']['App']['InstallNotificationDaemon']();
}

export function IsNotificationDaemonInstalled() {
  return window['go']['main']['App']['IsNotificationDaemonInstalled']();
}

export function IsNotificationDaemonRunning() {
  return window['go']['main']['App']['IsNotificationDaemonRunning']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenDocument(arg1) {
  return window['go']['main']['App']['OpenDocument'](arg1);
}

export function RebuildNotificationDaemon() {
  return window['go']['main']['App']['RebuildNotificationDaemon']();
}

export function Register(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3, arg4, arg5);
}

export function RequestLinkCourse(arg1, arg2) {
  return window['go']['main']['App']['RequestLinkCourse'](arg1, arg2);
}

export function SaveDocumentAs(arg1) {
  return window['go']['main']['App']['SaveDocumentAs'](arg1);
}

export function SendDocument(arg1) {
  return window['go']['main']['App']['SendDocument'](arg1);
}

export function StartNotificationDaemon() {
  return window['go']['main']['App']['StartNotificationDaemon']();
}

export function StopNotificationDaemon() {
  return window['go']['main']['App']['StopNotificationDaemon']();
}

export function Sync() {
  return window['go']['main']['App']['Sync']();
}

export function UninstallNotificationDaemon() {
  return window['go']['main']['App']['UninstallNotificationDaemon']();
}

export function UpdateAssignment(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAssignment'](arg1, arg2, arg3);
}

export function UpdateCourse(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateCourse'](arg1, arg2, arg3);
}

export function UpdateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3);
}

export function UpdateUser(arg1, arg2) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2);
}

export function UploadDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadDocument'](arg1, arg2, arg3);
}

export function UploadNewDocumentVersion(arg1) {
  return window['go']['main']['App']['UploadNewDocumentVersion'](arg1);
}
