// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {assignment} from '../models';
import {course} from '../models';
import {document} from '../models';
import {user} from '../models';
import {storage} from '../models';

export function CreateAssignment(arg1:assignment.Assignment):Promise<void>;

export function CreateCourse(arg1:course.Course):Promise<void>;

export function DeleteAssignment(arg1:assignment.LocalAssignment):Promise<void>;

export function DeleteCourse(arg1:course.Course):Promise<void>;

export function DeleteDocument(arg1:number):Promise<void>;

export function EnsureSSEConnection():Promise<void>;

export function GetAssignment(arg1:number):Promise<assignment.LocalAssignment>;

export function GetAssignmentDocuments(arg1:number):Promise<Array<document.LocalDocument>>;

export function GetAssignments():Promise<Array<assignment.LocalAssignment>>;

export function GetCourse(arg1:number):Promise<course.Course>;

export function GetCourses():Promise<Array<course.LocalCourse>>;

export function GetRemoteDocumentMetadata(arg1:number):Promise<Array<Record<string, any>>>;

export function GetSSEConnectionStatus():Promise<Record<string, any>>;

export function GetSubmissionDocuments(arg1:number):Promise<Array<document.LocalDocument>>;

export function GetSupportDocuments(arg1:number):Promise<Array<document.LocalDocument>>;

export function GetUser(arg1:number):Promise<user.User>;

export function GetUserStorageInfo():Promise<document.LocalDocumentCache>;

export function Greet(arg1:string):Promise<string>;

export function IsAuthenticated():Promise<storage.LocalCredentials>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function OpenDocument(arg1:number):Promise<void>;

export function ReconnectSSE():Promise<void>;

export function SaveDocumentAs(arg1:number):Promise<void>;

export function UpdateAssignment(arg1:assignment.LocalAssignment,arg2:string,arg3:string):Promise<void>;

export function UpdateCourse(arg1:course.Course):Promise<void>;

export function UploadDocument(arg1:number,arg2:string):Promise<document.LocalDocument>;

export function UploadNewDocumentVersion(arg1:number):Promise<document.LocalDocument>;
