// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {assignment} from '../models';
import {course} from '../models';
import {note} from '../models';
import {notifications} from '../models';
import {document} from '../models';
import {user} from '../models';
import {main} from '../models';

export function AcceptLink(arg1:string):Promise<void>;

export function CreateAssignment(arg1:assignment.LocalAssignment):Promise<void>;

export function CreateCourse(arg1:course.LocalCourse):Promise<void>;

export function CreateNote(arg1:note.LocalNote):Promise<void>;

export function DeleteAssignment(arg1:assignment.LocalAssignment):Promise<void>;

export function DeleteCourse(arg1:course.LocalCourse):Promise<void>;

export function DeleteDocument(arg1:number):Promise<void>;

export function DeleteNote(arg1:note.LocalNote):Promise<void>;

export function DeleteNotification(arg1:notifications.LocalNotification):Promise<void>;

export function Follow(arg1:number):Promise<boolean>;

export function GetAssignment(arg1:number):Promise<assignment.LocalAssignment>;

export function GetAssignmentDocuments(arg1:number):Promise<Array<document.LocalDocument>>;

export function GetAssignments():Promise<Array<assignment.LocalAssignment>>;

export function GetCourse(arg1:number):Promise<course.Course>;

export function GetCourseAssignments(arg1:course.LocalCourse):Promise<Array<assignment.LocalAssignment>>;

export function GetCourses():Promise<Array<course.LocalCourse>>;

export function GetCurrentUser():Promise<user.User>;

export function GetFollowers(arg1:number):Promise<main.FollowResponse>;

export function GetFollowing(arg1:number):Promise<main.FollowResponse>;

export function GetNetworkStatus():Promise<Record<string, any>>;

export function GetNotes():Promise<Array<note.LocalNote>>;

export function GetNotificationDaemonStatus():Promise<Record<string, any>>;

export function GetNotifications():Promise<Array<notifications.LocalNotification>>;

export function GetRemoteDocumentMetadata(arg1:number):Promise<Array<Record<string, any>>>;

export function GetRemoteUsers():Promise<Array<user.User>>;

export function GetSubmissionDocuments(arg1:number):Promise<Array<document.LocalDocument>>;

export function GetSupportDocuments(arg1:number):Promise<Array<document.LocalDocument>>;

export function GetUser(arg1:number):Promise<user.User>;

export function GetUserStorageInfo():Promise<document.StorageInfo>;

export function InstallNotificationDaemon():Promise<void>;

export function IsNotificationDaemonInstalled():Promise<boolean>;

export function IsNotificationDaemonRunning():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<user.User>;

export function Logout():Promise<void>;

export function OpenDocument(arg1:number):Promise<void>;

export function RebuildNotificationDaemon():Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<user.User>;

export function RequestLinkCourse(arg1:string,arg2:Array<number>):Promise<void>;

export function SaveDocumentAs(arg1:number):Promise<void>;

export function StartNotificationDaemon():Promise<void>;

export function StopNotificationDaemon():Promise<void>;

export function Sync():Promise<void>;

export function UninstallNotificationDaemon():Promise<void>;

export function UpdateAssignment(arg1:assignment.LocalAssignment,arg2:string,arg3:string):Promise<void>;

export function UpdateCourse(arg1:course.LocalCourse,arg2:string,arg3:string):Promise<void>;

export function UpdateNote(arg1:note.LocalNote,arg2:string,arg3:string):Promise<void>;

export function UpdateUser(arg1:string,arg2:string):Promise<user.User>;

export function UploadDocument(arg1:number,arg2:string):Promise<document.LocalDocument>;

export function UploadNewDocumentVersion(arg1:number):Promise<document.LocalDocument>;
