// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: internal/server/sse/grpc/notifications/messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_server_sse_grpc_notifications_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_sse_grpc_notifications_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_server_sse_grpc_notifications_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      uint32                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    uint32                 `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_server_sse_grpc_notifications_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_sse_grpc_notifications_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_server_sse_grpc_notifications_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetSenderId() uint32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetReceiverId() uint32 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *Message) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_server_sse_grpc_notifications_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_sse_grpc_notifications_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_server_sse_grpc_notifications_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_internal_server_sse_grpc_notifications_messages_proto protoreflect.FileDescriptor

const file_internal_server_sse_grpc_notifications_messages_proto_rawDesc = "" +
	"\n" +
	"5internal/server/sse/grpc/notifications/messages.proto\x12\rnotifications\"\x1f\n" +
	"\tHeartbeat\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"\x9f\x01\n" +
	"\aMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\rR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\rR\n" +
	"receiverId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\"$\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x99\x01\n" +
	"\x0eMessageService\x12@\n" +
	"\vSendMessage\x12\x16.notifications.Message\x1a\x17.notifications.Response\"\x00\x12E\n" +
	"\rSendHeartbeat\x12\x18.notifications.Heartbeat\x1a\x18.notifications.Heartbeat\"\x00B#Z!internal/server/sse/grpc/messagesb\x06proto3"

var (
	file_internal_server_sse_grpc_notifications_messages_proto_rawDescOnce sync.Once
	file_internal_server_sse_grpc_notifications_messages_proto_rawDescData []byte
)

func file_internal_server_sse_grpc_notifications_messages_proto_rawDescGZIP() []byte {
	file_internal_server_sse_grpc_notifications_messages_proto_rawDescOnce.Do(func() {
		file_internal_server_sse_grpc_notifications_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_server_sse_grpc_notifications_messages_proto_rawDesc), len(file_internal_server_sse_grpc_notifications_messages_proto_rawDesc)))
	})
	return file_internal_server_sse_grpc_notifications_messages_proto_rawDescData
}

var file_internal_server_sse_grpc_notifications_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_server_sse_grpc_notifications_messages_proto_goTypes = []any{
	(*Heartbeat)(nil), // 0: notifications.Heartbeat
	(*Message)(nil),   // 1: notifications.Message
	(*Response)(nil),  // 2: notifications.Response
}
var file_internal_server_sse_grpc_notifications_messages_proto_depIdxs = []int32{
	1, // 0: notifications.MessageService.SendMessage:input_type -> notifications.Message
	0, // 1: notifications.MessageService.SendHeartbeat:input_type -> notifications.Heartbeat
	2, // 2: notifications.MessageService.SendMessage:output_type -> notifications.Response
	0, // 3: notifications.MessageService.SendHeartbeat:output_type -> notifications.Heartbeat
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_server_sse_grpc_notifications_messages_proto_init() }
func file_internal_server_sse_grpc_notifications_messages_proto_init() {
	if File_internal_server_sse_grpc_notifications_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_server_sse_grpc_notifications_messages_proto_rawDesc), len(file_internal_server_sse_grpc_notifications_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_server_sse_grpc_notifications_messages_proto_goTypes,
		DependencyIndexes: file_internal_server_sse_grpc_notifications_messages_proto_depIdxs,
		MessageInfos:      file_internal_server_sse_grpc_notifications_messages_proto_msgTypes,
	}.Build()
	File_internal_server_sse_grpc_notifications_messages_proto = out.File
	file_internal_server_sse_grpc_notifications_messages_proto_goTypes = nil
	file_internal_server_sse_grpc_notifications_messages_proto_depIdxs = nil
}
